/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Splitwiser: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "groupId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "debtId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "debtor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "creditor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "DebtAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "groupId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "debtor",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creditor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "DebtSettled",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
          ],
          name: "acceptInvite",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_creditor",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          name: "addDebt",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address[]",
              name: "_creditors",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          name: "addExpense",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "balances",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "address[]",
              name: "_members",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "_token",
              type: "address",
            },
          ],
          name: "createGroup",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_person",
              type: "address",
            },
          ],
          name: "findDebts",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creditor",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
              ],
              internalType: "struct Splitwiser.PaymentToDo[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getUserGroups",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "groups",
          outputs: [
            {
              internalType: "string",
              name: "groupName",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "nextDebtId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_invited",
              type: "address",
            },
          ],
          name: "inviteMember",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
          ],
          name: "payDebtsForGroup",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "pendingGroupInvites",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_invited",
              type: "address",
            },
          ],
          name: "removeInvite",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
          ],
          name: "settleGroupDebts",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  84532: {
    Splitwiser: {
      address: "0xC2968f8c253178846a346c9f364c7A1799b71626",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "groupId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "debtId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "debtor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "creditor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "DebtAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "groupId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "debtor",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creditor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "DebtSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "groupId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "creator",
              type: "address",
            },
          ],
          name: "GroupCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
          ],
          name: "acceptInvite",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_creditor",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          name: "addDebt",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address[]",
              name: "_creditors",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          name: "addExpense",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "balances",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "address[]",
              name: "_members",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "_token",
              type: "address",
            },
          ],
          name: "createGroup",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_person",
              type: "address",
            },
          ],
          name: "findDebts",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creditor",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
              ],
              internalType: "struct Splitwiser.PaymentToDo[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getUserGroups",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "groups",
          outputs: [
            {
              internalType: "string",
              name: "groupName",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "nextDebtId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_invited",
              type: "address",
            },
          ],
          name: "inviteMember",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
          ],
          name: "payDebtsForGroup",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "pendingGroupInvites",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_invited",
              type: "address",
            },
          ],
          name: "removeInvite",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_groupId",
              type: "uint256",
            },
          ],
          name: "settleGroupDebts",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
